# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [161]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [162]:
df = pd.read_csv("cardekho_imputated.csv",index_col=[0])

In [163]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning
### Handling Missing values

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [164]:
## Check Null Values
##Check features with nan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [165]:
df.drop(columns=['car_name','brand'],axis=1,inplace=True)

In [166]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [167]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [168]:
num_features = [feature for feature in df.columns if df[feature].dtype!='O']
print("Number of numerical features:",len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype=='O']
print("Number of categorical features:",len(cat_features))
discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of discrete features:",len(discrete_features))
continuous_features = [feature for feature in num_features if feature not in discrete_features]
print("Number of continuous features:",len(continuous_features))

Number of numerical features: 7
Number of categorical features: 4
Number of discrete features: 2
Number of continuous features: 5

In [169]:
from sklearn.model_selection import train_test_split

In [170]:
X = df.drop('selling_price',axis=1)
y = df['selling_price']

In [171]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [172]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64

## Feature Encoding and Scaling
**One Hot Encoding for Columns which had lesser unique values and not ordinal**
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [173]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [174]:
len(df['model'].unique())

120

In [175]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [176]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [177]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [178]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [179]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [180]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [181]:
X_train['model'] = le.fit_transform(X_train['model'])

In [182]:
X_test['model'] = le.transform(X_test['model'])

In [183]:
X_train['model']

19357     24
14500    118
7766       7
7702      64
15924      4
        ...
7689      44
910      117
13595      7
10751    100
1476     100
Name: model, Length: 12328, dtype: int32

In [184]:
X_test['model']

3825      88
12160     13
9568     100
9798      10
16769     54
        ...
8722      89
4112      95
1400      95
17672     16
11217     49
Name: model, Length: 3083, dtype: int32

In [185]:
X_test['model'].value_counts()

model
89     198
88     170
7      157
118    155
25     151
      ...
66       1
110      1
37       1
17       1
33       1
Name: count, Length: 99, dtype: int64

In [186]:
X_train.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
19357,24,3,47000,Individual,Petrol,Automatic,19.12,1373,91.10,5
14500,118,3,8000,Dealer,Petrol,Manual,18.60,1197,81.83,5
7766,7,5,48000,Dealer,Petrol,Manual,23.95,998,67.05,5
7702,64,4,16303,Dealer,Petrol,Manual,25.17,799,53.30,5
15924,4,7,49000,Individual,Diesel,Automatic,17.11,1968,174.33,5

In [195]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [198]:
num_features = X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
      ("OneHotEncoder",oh_transformer,onehot_columns),
      ("StandardScaler",numeric_transformer,num_features)  
    ],remainder='passthrough'    
)

In [199]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [201]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.010130,-0.162919,-0.141905,-0.214122,-0.216284,-0.401404,24.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.010130,-0.897076,-0.266819,-0.553177,-0.432274,-0.401404,118.0
2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.345657,-0.144094,1.018347,-0.936540,-0.776646,-0.401404,7.0
3,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.677894,-0.740776,1.311413,-1.319903,-1.097020,-0.401404,64.0
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.318815,-0.125270,-0.624743,0.932115,1.722967,-0.401404,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12323,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.983288,0.138274,0.069486,-0.164034,-0.753347,-0.401404,44.0
12324,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.979997,0.834782,0.023845,-0.767012,-0.753347,-0.401404,117.0
12325,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.651052,0.232397,3.298014,-1.325683,-1.399919,-1.646938,7.0
12326,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.644470,0.270046,-0.194753,-0.815174,-0.777811,-0.401404,100.0
12327,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.312234,1.023027,-0.194753,-0.815174,-0.777811,-0.401404,100.0

## Model Training And Model Selection

In [215]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(true,predicted)
    return mae,mse,r2,rmse

In [216]:
models = {
    'Linear Regresssion': LinearRegression(),
    'Lasso': Lasso(),
    "Ridge": Ridge(),
    'K Neighbors Regressor': KNeighborsRegressor(),
    'Decision Tree':DecisionTreeRegressor(),
    'Random Forest Regressor':RandomForestRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    model_train_mae,model_train_mse,model_train_r2_score,model_train_rmse = evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_r2_score,model_test_rmse = evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    print("Model performance for training set")
    print("- R2_score: {:.4f}".format(model_train_r2_score))
    print("- Mean Squared Error: {:.4f}".format(model_train_mse))
    print("- Mean Squared Error: {:.4f}".format(model_train_mae))
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    
    print("----------------------------")
    
    print("Model performance for test set")
    print("- R2_score: {:.4f}".format(model_test_r2_score))
    print("- Mean Squared Error: {:.4f}".format(model_test_mse))
    print("- Mean Squared Error: {:.4f}".format(model_test_mae))
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    
    print("="*35)
    print('\n')

Linear Regresssion
Model performance for training set
- R2_score: 0.6119
- Mean Squared Error: 317671679549.0582
- Mean Squared Error: 269945.9125
- Root Mean Squared Error: 563623.7039
----------------------------
Model performance for test set
- R2_score: 0.7140
- Mean Squared Error: 206724155792.6784
- Mean Squared Error: 265984.5427
- Root Mean Squared Error: 454669.2818
===================================


Lasso
Model performance for training set
- R2_score: 0.6119
- Mean Squared Error: 317671683377.3568
- Mean Squared Error: 269944.1673
- Root Mean Squared Error: 563623.7073
----------------------------
Model performance for test set
- R2_score: 0.7140
- Mean Squared Error: 206724736215.5576
- Mean Squared Error: 265983.1434
- Root Mean Squared Error: 454669.9201
===================================


Ridge
Model performance for training set
- R2_score: 0.6119
- Mean Squared Error: 317672081810.4399
- Mean Squared Error: 269912.6734
- Root Mean Squared Error: 563624.0607
----------------------------
Model performance for test set
- R2_score: 0.7140
- Mean Squared Error: 206727875364.4814
- Mean Squared Error: 265947.6455
- Root Mean Squared Error: 454673.3722
===================================


K Neighbors Regressor
Model performance for training set
- R2_score: 0.8952
- Mean Squared Error: 85789969461.3887
- Mean Squared Error: 84533.9066
- Root Mean Squared Error: 292899.2480
----------------------------
Model performance for test set
- R2_score: 0.8782
- Mean Squared Error: 88056498253.5274
- Mean Squared Error: 107506.8197
- Root Mean Squared Error: 296743.1520
===================================


Decision Tree
Model performance for training set
- R2_score: 0.9995
- Mean Squared Error: 377083872.7558
- Mean Squared Error: 4832.1463
- Root Mean Squared Error: 19418.6476
----------------------------
Model performance for test set
- R2_score: 0.5943
- Mean Squared Error: 293258252808.3442
- Mean Squared Error: 134687.2283
- Root Mean Squared Error: 541533.2426
===================================


Random Forest Regressor
Model performance for training set
- R2_score: 0.9768
- Mean Squared Error: 19011855045.3727
- Mean Squared Error: 39762.5128
- Root Mean Squared Error: 137883.4836
----------------------------
Model performance for test set
- R2_score: 0.9178
- Mean Squared Error: 59431762104.0892
- Mean Squared Error: 100014.5637
- Root Mean Squared Error: 243786.3042
===================================

In [205]:
import numpy as np

In [217]:
knn_params = {"n_neighbors":[2,3,10,20,40,50]}
rf_params ={
    "max_depth":[5,8,15,None,10],
    "max_features":[5,7,'auto',8],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[100,200,500,1000]
}

In [218]:
randomcv_models = [("KNN",KNeighborsRegressor(),knn_params),
                   ("RF",RandomForestRegressor(),rf_params)
                   ]

In [219]:
from sklearn.model_selection import RandomizedSearchCV
model_param = {}

for name,model,params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1
                                )
    random.fit(X_train,y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"----------------Best Params for {model_name}------------------")
    print(model_param[name])

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
72 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
57 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [0.86903748 0.85484521 0.79068843 0.84086694        nan 0.84733173
 0.84754298 0.85323032 0.78292383 0.84919554 0.85624921 0.80883585
 0.85493334 0.85729856        nan 0.86201674 0.86590577 0.84424212
 0.80386053 0.84237553 0.83596238 0.85518825 0.85048087 0.86167292
 0.85883185 0.84713825 0.85439633 0.8484353  0.86420916 0.87298323
        nan 0.86008389        nan        nan        nan 0.87254639
 0.84488083 0.85827794 0.8051056         nan 0.8446633  0.8101371
        nan 0.86445419 0.85237276 0.79208051        nan        nan
 0.85249158        nan 0.86135926 0.78219943 0.85149611 0.85038953
 0.85811177        nan 0.80269712 0.84938034 0.86577702        nan
        nan 0.78711158 0.85860067 0.87359449 0.85327964 0.8619765
 0.84921373 0.86771372        nan        nan 0.86670142        nan
 0.86953675 0.84740473 0.84593755        nan 0.85285948 0.80378604
        nan        nan 0.78634196        nan        nan 0.85245252
 0.86461236 0.8096174  0.85754734 0.87177683 0.85608815 0.84453843
 0.86145544 0.83177042 0.86812376 0.84907664 0.84159909 0.8686749
 0.85809082        nan 0.85387967        nan]
  warnings.warn(

----------------Best Params for KNN------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 15}
----------------Best Params for RF------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 15}

In [222]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=500, min_samples_split=2, max_features=8, max_depth=15, 
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=500, n_jobs=-1)
    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae,model_train_mse,model_train_r2_score,model_train_rmse = evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_r2_score,model_test_rmse = evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    print("Model performance for training set")
    print("- R2_score: {:.4f}".format(model_train_r2_score))
    print("- Mean Squared Error: {:.4f}".format(model_train_mse))
    print("- Mean Squared Error: {:.4f}".format(model_train_mae))
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    
    print("----------------------------")
    
    print("Model performance for test set")
    print("- R2_score: {:.4f}".format(model_test_r2_score))
    print("- Mean Squared Error: {:.4f}".format(model_test_mse))
    print("- Mean Squared Error: {:.4f}".format(model_test_mae))
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    
    print("="*35)
    print('\n')

Random Forest Regressor
Model performance for training set
- R2_score: 0.9790
- Mean Squared Error: 17161157653.5074
- Mean Squared Error: 53372.5675
- Root Mean Squared Error: 131000.6017
----------------------------
Model performance for test set
- R2_score: 0.9357
- Mean Squared Error: 46472243384.3233
- Mean Squared Error: 94822.9798
- Root Mean Squared Error: 215574.2178
===================================


K-Neighbors Regressor
Model performance for training set
- R2_score: 0.2753
- Mean Squared Error: 593195894610.8929
- Mean Squared Error: 280528.8034
- Root Mean Squared Error: 770192.1154
----------------------------
Model performance for test set
- R2_score: 0.3289
- Mean Squared Error: 485108205623.6254
- Mean Squared Error: 285348.5070
- Root Mean Squared Error: 696497.0966
===================================

In [187]:
# le.classes_

In [188]:
# def handle_unseen(label):
#     return label if label in le.classes_ else 'unknown'

In [189]:
# le.classes_ = np.append(le.classes_,'unknown')

In [190]:
# le.classes_

In [191]:
# X_test['model'] = X_test['model'].apply(handle_unseen)

In [192]:
# X_test['model'].value_counts()