In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_genderreg.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_georeg.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scalerreg.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1)
    ]
)
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

c:\Users\Dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir = 'regressionlogs/fit/'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [16]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [17]:
history = model.fit(
    X_train,y_train,
    validation_data = (X_test,y_test),
    epochs =100,
    callbacks = [early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 100363.0781 - mae: 100363.0781 - val_loss: 98465.2031 - val_mae: 98465.2031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 99430.6250 - mae: 99430.6250 - val_loss: 96566.2656 - val_mae: 96566.2656
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 96147.7812 - mae: 96147.7812 - val_loss: 91764.3047 - val_mae: 91764.3047
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 89790.5625 - mae: 89790.5625 - val_loss: 83982.5078 - val_mae: 83982.5078
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 80893.6641 - mae: 80893.6641 - val_loss: 74610.9688 - val_mae: 74610.9688
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 71136.2266 - mae: 71136.2266 - val_loss: 65564.0938 - val_mae: 65564.0938
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 62483.1406 - mae: 62483.1406 - val_loss: 58507.0625 - val_mae: 58507.0625
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56450.0586 - mae: 56450.0586 - val_loss: 54146.1914 - val_mae: 54146.1914
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 53005.6680 - mae: 53005.6680 - val_loss: 52012.7891 - val_mae: 52012.7891
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 51403.1484 - mae: 51403.1484 - val_loss: 51269.3477 - val_mae: 51269.3477
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 50749.6680 - mae: 50749.6680 - val_loss: 50971.7734 - val_mae: 50971.7734
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50465.7930 - mae: 50465.7930 - val_loss: 50834.2422 - val_mae: 50834.2422
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50308.8047 - mae: 50308.8047 - val_loss: 50748.5742 - val_mae: 50748.5742
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 50207.0547 - mae: 50207.0547 - val_loss: 50674.1484 - val_mae: 50674.1484
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50134.6484 - mae: 50134.6484 - val_loss: 50623.2461 - val_mae: 50623.2461
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50084.5156 - mae: 50084.5156 - val_loss: 50571.4258 - val_mae: 50571.4258
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50034.9336 - mae: 50034.9336 - val_loss: 50524.4609 - val_mae: 50524.4609
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49995.1445 - mae: 49995.1445 - val_loss: 50487.9883 - val_mae: 50487.9883
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49959.6914 - mae: 49959.6914 - val_loss: 50453.3633 - val_mae: 50453.3633
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49926.1250 - mae: 49926.1250 - val_loss: 50433.2539 - val_mae: 50433.2539
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49896.7461 - mae: 49896.7461 - val_loss: 50413.0703 - val_mae: 50413.0703
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49870.1758 - mae: 49870.1758 - val_loss: 50396.3945 - val_mae: 50396.3945
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49843.9961 - mae: 49843.9961 - val_loss: 50378.6523 - val_mae: 50378.6523
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49818.9336 - mae: 49818.9336 - val_loss: 50361.8398 - val_mae: 50361.8398
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49796.9141 - mae: 49796.9141 - val_loss: 50355.7656 - val_mae: 50355.7656
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49777.7188 - mae: 49777.7188 - val_loss: 50341.0938 - val_mae: 50341.0938
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49756.0938 - mae: 49756.0938 - val_loss: 50327.1445 - val_mae: 50327.1445
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49737.9961 - mae: 49737.9961 - val_loss: 50322.8359 - val_mae: 50322.8359
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49716.2422 - mae: 49716.2422 - val_loss: 50315.1250 - val_mae: 50315.1250
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49701.9062 - mae: 49701.9062 - val_loss: 50317.1055 - val_mae: 50317.1055
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49684.1953 - mae: 49684.1953 - val_loss: 50304.1328 - val_mae: 50304.1328
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49667.6250 - mae: 49667.6250 - val_loss: 50288.1250 - val_mae: 50288.1250
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49657.3477 - mae: 49657.3477 - val_loss: 50289.1836 - val_mae: 50289.1836
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49646.1797 - mae: 49646.1797 - val_loss: 50288.5195 - val_mae: 50288.5195
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49633.6992 - mae: 49633.6992 - val_loss: 50277.2773 - val_mae: 50277.2773
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49618.4844 - mae: 49618.4844 - val_loss: 50268.7812 - val_mae: 50268.7812
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49609.4648 - mae: 49609.4648 - val_loss: 50269.8516 - val_mae: 50269.8516
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49600.1250 - mae: 49600.1250 - val_loss: 50250.8281 - val_mae: 50250.8281
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49590.3711 - mae: 49590.3711 - val_loss: 50248.4219 - val_mae: 50248.4219
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49581.0742 - mae: 49581.0742 - val_loss: 50257.0469 - val_mae: 50257.0469
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49568.8672 - mae: 49568.8672 - val_loss: 50242.3555 - val_mae: 50242.3555
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49563.3984 - mae: 49563.3984 - val_loss: 50246.4805 - val_mae: 50246.4805
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49554.0234 - mae: 49554.0234 - val_loss: 50244.5312 - val_mae: 50244.5312
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49545.3086 - mae: 49545.3086 - val_loss: 50248.2461 - val_mae: 50248.2461
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49539.3789 - mae: 49539.3789 - val_loss: 50252.4141 - val_mae: 50252.4141
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49533.1719 - mae: 49533.1719 - val_loss: 50251.3242 - val_mae: 50251.3242
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49521.2773 - mae: 49521.2773 - val_loss: 50236.2930 - val_mae: 50236.2930
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49518.0117 - mae: 49518.0117 - val_loss: 50244.1992 - val_mae: 50244.1992
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49509.3750 - mae: 49509.3750 - val_loss: 50255.7969 - val_mae: 50255.7969
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49501.0625 - mae: 49501.0625 - val_loss: 50257.5352 - val_mae: 50257.5352
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49499.5000 - mae: 49499.5000 - val_loss: 50255.1602 - val_mae: 50255.1602
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49489.1680 - mae: 49489.1680 - val_loss: 50260.7539 - val_mae: 50260.7539
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49485.1406 - mae: 49485.1406 - val_loss: 50266.7539 - val_mae: 50266.7539
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49477.6680 - mae: 49477.6680 - val_loss: 50259.2148 - val_mae: 50259.2148
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49472.1328 - mae: 49472.1328 - val_loss: 50258.6992 - val_mae: 50258.6992
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49464.1836 - mae: 49464.1836 - val_loss: 50270.4336 - val_mae: 50270.4336
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49462.0352 - mae: 49462.0352 - val_loss: 50263.5703 - val_mae: 50263.5703

In [18]:
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 12392), started 0:00:15 ago. (Use '!kill 12392' to kill it.)